### PR TITLE
Add stats to runc dump/restore

### PR DESCRIPTION
**Pull request by yashanand1910**
## Describe your changes
Currently, stats are only returned in response for process C/R.

Also look at: https://github.com/cedana/cedana-api/pull/23

## Issue ticket number
CED-640

## Checklist before requesting a review
- [x] Have I performed a self-review?
- [x] Have I added regression or unit tests (where it makes sense) for my changes?
- [x] Have I updated the README if changes have resulted in it being out of date?
- [x] Have I checked to ensure my PR only introduces the changes it's intended to? E.g. No extraneous formatting changes.
- [ ] Is this a breaking change? If yes, please describe areas affected and request reviews from developer stakeholders.

### CODE REVIEW

**Review by nravic — CHANGES_REQUESTED** [review]
Unless I'm mistaken this is missing actually calculating the stats. Take a look at cedana/pkg/api/process.go to see how the stats are generated

**Comment by nravic** [comment]
> Unless I'm mistaken this is missing actually calculating the stats. Take a look at cedana/pkg/api/process.go to see how the stats are generated

I am mistaken! Forgot I added it lol

**Comment by nravic** [comment]
I merged cedana-api, after you bump it and regenerate here you should be g2g

**Comment by yashanand1910** [comment]
@nravic Done. Can merge after CI.

**Review by nravic — APPROVED** [review]
lgtm

**Pull request merged**
