### PR TITLE
Refactor and more regression tests to catch changes to base API functionality 

### PR DESCRIPTION
**Pull request by nravic**

### CODE REVIEW

**Comment by lianakoleva** [comment]
@yashanand1910 please provide justification for the rearranging of imports and the addition and removal of whitespace in `cedana_bindings.py`. this makes the commit more messy. feel free to open a formatting commit if you want to make formatting changes.

**Comment by yashanand1910** [comment]
@lianakoleva Fair point. I think this one was by accident while changes were being made to `cedana_bindings.py`, you can let it pass. I'll put up a separate PR with formatting config for Py and Go files for consistency.

**Comment by lianakoleva** [comment]
@nravic would appreciate if you could also strip extraneous formatting changes from this PR

**Comment by nravic** [comment]
> @nravic would appreciate if you could also strip extraneous formatting changes from this PR

@lianakoleva sure! did you look into adding Black yesterday? I think it'd be a lot easier for reviews in the future if everyone was just using the same formatter or something so this isn't a regular issue

**Comment by lianakoleva** [comment]
@nravic i added an issue for that (: in the meantime we can stick to only pushing essential edits, it hasn't been an issue before this PR

**Comment by lianakoleva** [comment]
lgtm
Screenshot from 2024-05-23 12-07-24

**Review by lianakoleva — APPROVED** [review]
lgtm

**Pull request merged**
