### PR TITLE
Deploy `cedana-bench` to CI

### PR DESCRIPTION
**Pull request by yashanand1910**
## Describe your changes
- Adds a PR job to run benchmark and post comparison w/ last patch on the PR as well as Slack to help catch performance regressions.
- Adds a release job to run benchmark and publish results to bigquery along with a post on Slack. All similar to the GPU benchmarks.
- Adds a manual workflow to trigger the benchmark manually on any branch, including an option to publish results to bigquery.

## Issue ticket number
CED-646

## Checklist before requesting a review
- [x] Have I performed a self-review?
- [x] Have I added regression or unit tests (where it makes sense) for my changes?
- [x] Have I updated the README if changes have resulted in it being out of date?
- [x] Have I checked to ensure my PR only introduces the changes it's intended to? E.g. No extraneous formatting changes.
- [ ] Is this a breaking change? If yes, please describe areas affected and request reviews from developer stakeholders.

### CODE REVIEW

**Comment by yashanand1910** [comment]
Previous results don't exist, so you won't see a comparison until we do a release.

**Comment by nravic** [comment]
freaking beautiful

**Comment by yashanand1910** [comment]
> Looks great, you can get rid of the old benchmark in the weekly.yml as well (and maybe run this weekly too?)

That should be a separate PR. The correctness tests are part of the old benchmark, will have to clean it up.

**Review by nravic — APPROVED** [review]
I can do the cleanup, I have a separate ticket for it anyway

**Pull request merged**
