### PR TITLE
Directly set stdin/stderr of managed job instead of scanning

### PR DESCRIPTION
**Pull request by yashanand1910**
## Describe your changes
Currently, we are scanning the stdout/stderr-pipe and writing to a log file in a background routine, which is non-performant. Instead, it is possible to simply set the job's stdout/stderr before spawning the process.

## Issue ticket number 
CED-614

## Checklist before requesting a review
- [x] Have I performed a self-review?
- [x] Have I added regression or unit tests (where it makes sense) for my changes?
- [x] Have I updated the README if changes have resulted in it being out of date?
- [x]  Have I checked to ensure my PR only introduces the changes it's intended to? E.g. No extraneous formatting changes.
- [ ] Is this a breaking change? If yes, please describe areas affected and request reviews from developer stakeholders.

### CODE REVIEW

**Comment by nravic** [comment]
regression test failing

**Comment by yashanand1910** [comment]
@nravic This PR does not touch containerd rootfs. I think this PR is failing on main branch itself, or is a flaky test.

I have opened #295, to ensure tests also run on the main branch each time.

**Comment by yashanand1910** [comment]
@nravic Looks like they are indeed flaky. It just passed on a rerun.

**Comment by yashanand1910** [comment]
@bsmithai Is this due to the TCP issue you mentioned today?

**Pull request merged**
