### PR TITLE
Fix runc --root default values

### PR DESCRIPTION
**Pull request by yashanand1910**
## Describe your changes
The default value for `--root` in `cedana restore runc …` correctly does not work (bug). Also changes the default value for dump to default for consistency.

## Issue ticket number 
CED-403

## Checklist before requesting a review
- [x] Have I performed a self-review?
- [ ] Have I added regression or unit tests (where it makes sense) for my changes?
- [ ] Have I updated the README if changes have resulted in it being out of date?
- [x]  Have I checked to ensure my PR only introduces the changes it's intended to? E.g. No extraneous formatting changes.
- [ ] Is this a breaking change? If yes, please describe areas affected and request reviews from developer stakeholders.

### CODE REVIEW

**Comment by nravic** [comment]
Your changes make sense! I'd merge in and resolve the conflicts from the latest push and take a look again - some functions got renamed for legibility and I think the renaming aligns with what we talked about earlier today. 

lgtm otherwise

**Comment by yashanand1910** [comment]
@nravic Fixed. Sorry, the base was earlier outdated. Now the diff should be cleaner.

**Comment by nravic** [comment]
ok nice, and this only affects cli commands, so don't need review from @bsmithai . Approved

**Review by nravic — APPROVED** [review]
lgtm

**Pull request merged**
